table fact_risk_scores
	lineageTag: a6f5cc72-a8ed-4151-af17-dd74eba2deff

	column policy_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: a74ccbaf-7613-48d5-9646-41e487ba954d
		summarizeBy: none
		sourceColumn: policy_id

		annotation SummarizationSetBy = Automatic

	column customer_id
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 4b115f89-0c58-4f0e-b11a-1ce065d181ad
		summarizeBy: none
		sourceColumn: customer_id

		annotation SummarizationSetBy = Automatic

	column scored_for_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 24f47090-ec95-432b-90e8-06f6e92a339e
		summarizeBy: none
		sourceColumn: scored_for_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column risk_score
		dataType: double
		lineageTag: 28a74319-906c-4420-9b74-886ee2a8547b
		summarizeBy: sum
		sourceColumn: risk_score

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column premium_amount
		dataType: double
		isHidden
		lineageTag: 05d6cf32-e30b-4ebe-8dee-b6fa8bfaaae6
		summarizeBy: sum
		sourceColumn: premium_amount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column risk_band
		dataType: string
		lineageTag: 2e4f168b-496e-4198-9fe3-4a605fe97ab1
		summarizeBy: none
		sourceColumn: risk_band
		sortByColumn: risk_band_order

		annotation SummarizationSetBy = Automatic

	column premium_at_risk
		dataType: double
		lineageTag: 7f69675e-41ad-4cbe-a306-cfd14da66736
		summarizeBy: sum
		sourceColumn: premium_at_risk

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column risk_band_order
		dataType: int64
		isHidden
		formatString: 0
		lineageTag: 3c8b1e5f-7a2d-4b9e-a6f1-0d4e8c2b7a95
		summarizeBy: none
		sourceColumn: risk_band_order

		annotation SummarizationSetBy = Automatic

	partition fact_risk_scores = m
		mode: import
		source =
				let
				  Source = PostgreSQL.Database("aws-0-ap-southeast-2.pooler.supabase.com:5432", "postgres"),
				  #"Navigation 1" = Source{[Schema = "public", Item = "fact_risk_scores"]}[Data],
				  // Bands are an ordered scale, so charts sort them Low to Very high, not A to Z.
				  // Built here, not in DAX: a DAX column made from risk_band can't also sort it.
				  #"Added risk_band_order" = Table.AddColumn(
				    #"Navigation 1",
				    "risk_band_order",
				    each List.PositionOf({"Low", "Medium", "High", "Very high"}, [risk_band]) + 1,
				    Int64.Type
				  )
				in
				  #"Added risk_band_order"

	annotation PBI_ResultType = Table

